feat: make config more generic

diff --git a/dot_bashrc.tmpl b/dot_bashrc.tmpl
--- a/dot_bashrc.tmpl
+++ b/dot_bashrc.tmpl
@@ -5,6 +5,16 @@
 # If not running interactively, don't do anything
 [[ $- != *i* ]] && return
 
+# Source global definitions
+if [ -f /etc/bashrc ]; then
+    . /etc/bashrc
+fi
+
+# User specific environment
+if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
+    export PATH="$HOME/.local/bin:$HOME/bin:$PATH"
+fi
+
 alias ls='ls --color=auto'
 alias grep='grep --color=auto'
 
@@ -42,3 +52,6 @@ export NVM_DIR="$HOME/.nvm"
 alias pipenv="python3 -m pipenv"
 
 . <(flux completion bash)
+
+# cleanup rc var if set
+unset rc
