feat: more git aliases

diff --git a/scripts/executable_setup-misc-aliases.bash.tmpl b/scripts/executable_setup-misc-aliases.bash.tmpl
--- a/scripts/executable_setup-misc-aliases.bash.tmpl
+++ b/scripts/executable_setup-misc-aliases.bash.tmpl
@@ -277,10 +277,10 @@ browser() {
 gitmain() {
   current_branch=$(git rev-parse --abbrev-ref HEAD)
   if [[ "$current_branch" != "main" && "$current_branch" != "master" ]]; then
-    git fetch origin main:main
-    git checkout main
+    git fetch origin main:main || return 1
+    git checkout main || return 1
   else
-    git pull origin main
+    git pull origin main || return 1
   fi
   delete-local-refs
 }
@@ -320,6 +320,27 @@ gitopen() {
 }
 complete -d gitopen
 
+# git commit to branch helper
+_git_branch_helper() {
+  # convert commit message to branch syntax (e.g. "fix/something-again")
+  # logic:
+  #   sed: try converting ": " to "/" or keep original string
+  #   tr: replace " " with "-"
+  #   tr: convert to lowercase
+  echo "$*" | sed -E 's/^([a-z]+):[[:space:]]*(.*)$/\1\/\2/' | tr ' ' '-' | tr '[:upper:]' '[:lower:]'
+}
+
+# git commit message completer
+_git_commit_message_completion() {
+  COMP_WORDBREAKS=${COMP_WORDBREAKS//:}
+  # declare -p COMP_CWORD COMP_WORDS # DEBUG
+
+  [[ $COMP_CWORD -eq 1 ]] &&
+    COMPREPLY=( $(compgen -W "feat: chore: revert: fix: refactor: test: docs: style: perf:" -- "${COMP_WORDS[1]}") )
+  [[ $COMP_CWORD -eq 2 ]] &&
+    COMPREPLY=( $(compgen -W "add adjust rm remove include bump sw switch fix" -- "${COMP_WORDS[2]}") )
+}
+
 # git branch and commit
 gitcb() {
     local message="$*" # something like "fix: something again"
@@ -344,12 +365,7 @@ gitcb() {
         esac
     fi
 
-    # convert message to "fix/something-again" for branch
-    # logic:
-    #   sed: try converting ": " to "/" or keep original string
-    #   tr: replace " " with "-"
-    #   tr: convert to lowercase
-    local branch=$(echo "$message" | sed -E 's/^([a-z]+):[[:space:]]*(.*)$/\1\/\2/' | tr ' ' '-' | tr '[:upper:]' '[:lower:]') 
+    local branch=$(_git_branch_helper "$message") 
 
     git switch -c "$branch"
     git add .
@@ -358,16 +374,49 @@ gitcb() {
 
     gitopen
 }
-_gitcb() {
-  COMP_WORDBREAKS=${COMP_WORDBREAKS//:}
-  # declare -p COMP_CWORD COMP_WORDS # DEBUG
+complete -F _git_commit_message_completion gitcb
 
-  [[ $COMP_CWORD -eq 1 ]] &&
-    COMPREPLY=( $(compgen -W "feat: chore: revert: fix: refactor: test: docs: style: perf:" -- "${COMP_WORDS[1]}") )
-  [[ $COMP_CWORD -eq 2 ]] &&
-    COMPREPLY=( $(compgen -W "add adjust rm remove include bump sw switch fix" -- "${COMP_WORDS[2]}") )
+# git branch
+gitb() {
+    local input="$*" # something like "fix: something again"
+
+    if [[ -z "$input" ]]; then
+        echo "Usage: gitcb \"<branch name>\""
+        return 1
+    fi
+
+    local branch=$(_git_branch_helper "$input") 
+
+    git switch -c "$branch"
+    git push -u origin "$branch"
 }
-complete -F _gitcb gitcb
+complete -F _git_commit_message_completion gitb
+
+# git commit
+gitc() {
+    local input="$*" # something like "fix: something again"
+
+    if [[ -z "$input" ]]; then
+        echo "Usage: gitcb \"<commit message>\""
+        return 1
+    fi
+
+    if [[ "$current_branch" == "main" || "$current_branch" == "master" ]]; then
+        echo "You are currently on branch: $current_branch."
+        echo "Typically you use this command (git commit) for creating a commit on a feature branch."
+        echo "If this wasn't intentional you might want to create a branch (and commit) using 'gitb' or 'gitcb'"
+        read -rp "Continue creating commit on main? [y/N] " confirm
+        case "$confirm" in
+            [yY][eE][sS]|[yY]) ;;
+            *) echo "Aborted."; return 1 ;;
+        esac
+    fi
+
+    git add .
+    git commit -nm "$input"
+    git push
+}
+complete -F _git_commit_message_completion gitc
 
 # automatic semver tagging
 gittag() {
